[11/22/2015 5:30:28 PM] ...............................
[11/22/2015 5:30:28 PM] ..........New History..........
[11/22/2015 5:30:28 PM] ...............................
[11/22/2015 5:30:54 PM] ...............................
[11/22/2015 5:30:54 PM] ..........New History..........
[11/22/2015 5:30:54 PM] ...............................
[11/22/2015 5:32:35 PM] ...............................
[11/22/2015 5:32:35 PM] ..........New History..........
[11/22/2015 5:32:35 PM] ...............................
[11/22/2015 5:33:48 PM] ...............................
[11/22/2015 5:33:48 PM] ..........New History..........
[11/22/2015 5:33:48 PM] ...............................
[11/22/2015 6:27:16 PM] ...............................
[11/22/2015 6:27:16 PM] ..........New History..........
[11/22/2015 6:27:16 PM] ...............................
[11/22/2015 8:48:06 PM] ...............................
[11/22/2015 8:48:06 PM] ..........New History..........
[11/22/2015 8:48:06 PM] ...............................
[11/22/2015 8:50:52 PM] ...............................
[11/22/2015 8:50:52 PM] ..........New History..........
[11/22/2015 8:50:52 PM] ...............................
[11/22/2015 10:43:50 PM] ...............................
[11/22/2015 10:43:50 PM] ..........New History..........
[11/22/2015 10:43:50 PM] ...............................
[11/22/2015 10:43:50 PM] System.IO.IOException: Read failure ---> System.Net.Sockets.SocketException: 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다.

  at System.Net.Sockets.Socket.Receive (System.Byte[] buffer, Int32 offset, Int32 size, SocketFlags flags) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.NetworkStream.Read (System.Byte[] buffer, Int32 offset, Int32 size) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.Read (System.Byte[] buffer, Int32 offset, Int32 size) [0x00000] in <filename unknown>:0 
  at LoboNet.Connection.Read (System.Byte[] buffer, Int32 size, Int32 offset) [0x00000] in <filename unknown>:0 
  at TeraTaleNet.PacketStream.Read () [0x00000] in <filename unknown>:0 
  at TeraTaleNet.Messenger.Receiver () [0x00000] in <filename unknown>:0 
[11/22/2015 10:43:50 PM] System.IO.IOException: Read failure ---> System.Net.Sockets.SocketException: 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다.

  at System.Net.Sockets.Socket.Receive (System.Byte[] buffer, Int32 offset, Int32 size, SocketFlags flags) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.NetworkStream.Read (System.Byte[] buffer, Int32 offset, Int32 size) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.Read (System.Byte[] buffer, Int32 offset, Int32 size) [0x00000] in <filename unknown>:0 
  at LoboNet.Connection.Read (System.Byte[] buffer, Int32 size, Int32 offset) [0x00000] in <filename unknown>:0 
  at TeraTaleNet.PacketStream.Read () [0x00000] in <filename unknown>:0 
  at TeraTaleNet.Messenger.Receiver () [0x00000] in <filename unknown>:0 
[11/23/2015 8:18:56 PM] ...............................
[11/23/2015 8:18:56 PM] ..........New History..........
[11/23/2015 8:18:56 PM] ...............................
[11/23/2015 8:21:14 PM] ...............................
[11/23/2015 8:21:14 PM] ..........New History..........
[11/23/2015 8:21:14 PM] ...............................
[11/23/2015 8:21:45 PM] ...............................
[11/23/2015 8:21:45 PM] ..........New History..........
[11/23/2015 8:21:45 PM] ...............................
[11/23/2015 8:22:13 PM] ...............................
[11/23/2015 8:22:13 PM] ..........New History..........
[11/23/2015 8:22:13 PM] ...............................
[11/23/2015 8:23:31 PM] ...............................
[11/23/2015 8:23:31 PM] ..........New History..........
[11/23/2015 8:23:31 PM] ...............................
